#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#define APP_CONFIG_CAN_MAX_DATA_LENGTH 8U
#define APP_CONFIG_CAN_STD_ID_MAX 0x7FFU
#define APP_CONFIG_CAN_TX_FRAME_CAPACITY 16U
#define APP_CONFIG_CAN_RX_QUEUE_LENGTH 32U

#define APP_CONFIG_DM_MOTOR_COUNT 4U
#define APP_CONFIG_DJI_WHEEL_COUNT 2U
#define APP_CONFIG_IMU_AXIS_COUNT 3U

#define APP_CONFIG_DM_FRAME_LENGTH 8U
#define APP_CONFIG_DJI_FEEDBACK_LENGTH 8U
#define APP_CONFIG_DJI_COMMAND_LENGTH 8U

#define APP_CONFIG_DJI_CURRENT_TX_ID 0x200U
#define APP_CONFIG_DJI_LEFT_FEEDBACK_ID 0x201U
#define APP_CONFIG_DJI_RIGHT_FEEDBACK_ID 0x202U

#define APP_CONFIG_DM_LEFT_FRONT_TX_ID 0x002U
#define APP_CONFIG_DM_LEFT_FRONT_RX_ID 0x002U
#define APP_CONFIG_DM_LEFT_BACK_TX_ID 0x001U
#define APP_CONFIG_DM_LEFT_BACK_RX_ID 0x001U
#define APP_CONFIG_DM_RIGHT_FRONT_TX_ID 0x004U
#define APP_CONFIG_DM_RIGHT_FRONT_RX_ID 0x004U
#define APP_CONFIG_DM_RIGHT_BACK_TX_ID 0x003U
#define APP_CONFIG_DM_RIGHT_BACK_RX_ID 0x003U

#define APP_CONFIG_DM_LEFT_DIRECTION 1
#define APP_CONFIG_DM_RIGHT_DIRECTION (-1)

#define APP_CONFIG_CAN_TASK_PERIOD_TICKS 1U
#define APP_CONFIG_CHASSIS_TASK_PERIOD_TICKS 2U
#define APP_CONFIG_IMU_TASK_PERIOD_TICKS 1U

/*
 * 控制器第一阶段只计算中间状态和安全输出。
 * 该宏保持 0 时，即使控制器配置允许输出，也不会解除零力矩/零电流封锁。
 */
#define APP_CONFIG_CHASSIS_CONTROLLER_OUTPUT_ENABLE 0U

#define APP_CONFIG_DM_ONLINE_TIMEOUT_TICKS 50U
#define APP_CONFIG_DJI_ONLINE_TIMEOUT_TICKS 50U
#define APP_CONFIG_CAN_TX_ERROR_LIMIT 1000U

#define APP_CONFIG_IMU_INIT_RETRY_TICKS 100U
#define APP_CONFIG_IMU_SPI_TIMEOUT_MS 2U
#define APP_CONFIG_IMU_BIAS_SAMPLE_COUNT 200U
#define APP_CONFIG_IMU_DEFAULT_DT_SEC 0.001f
#define APP_CONFIG_IMU_COMPLEMENTARY_ALPHA 0.98f

typedef enum
{
    APP_CAN_BUS_UNKNOWN = 0,
    APP_CAN_BUS_FDCAN1,
    APP_CAN_BUS_FDCAN2,
} app_can_bus_t;

#ifdef __cplusplus
}
#endif

#endif
